### ISSUE TITLE
Some listed input files could not be found

### ISSUE THREAD

**Issue by toddajohnson** [gatk-workflows/gatk4-exome-analysis-pipeline#2]
Trying to get this running on some open access exome sequencing data from the Texas Cancer Research Biobank using our local server.

I've downloaded the hg38 reference files from the Broad or Google cloud, but on neither could I find the following files that are listed in ExomeGermlineSingleSample.inputs.json:
Homo_sapiens_assembly38.contam.UD
Homo_sapiens_assembly38.contam.bed
Homo_sapiens_assembly38.contam.mu

I tried just deleting the lines that reference those files, but that just resulted in Cromwell complaining "No value for field 'contamination_sites_ud'"

Thanks,
Todd

**Comment by LeonMaiShi** [comment]
Hi Todd,

You can find them in the [Google Cloud bucket](https://console.cloud.google.com/storage/browser/broad-references/hg38/v0/).

Best,
Leon
