### ISSUE TITLE
wdl parsing errors

### ISSUE THREAD

**Issue by marysweet** [gatk-workflows/gatk4-exome-analysis-pipeline#4]
I'm excited to use this pipeline, I've been looking forward to it for a while!

I'm trying to run it through GCP/Cromwell but am encountering errors with running the wdl file. These are the same errors whether I submit them through GCP/Cromwell or if I validate the wdl using the wdltool-0.14.jar.

> ERROR: Finished parsing without consuming all tokens.
> 
> version 1.0
> ^

I tried commenting out the version 1.0 line, but then I get this error:

> ERROR: Unexpected symbol (line 43, col 3) when parsing '_gen10'.
> 
> Expected rbrace, got input.
> 
>   input {
>   ^
>
>$workflow = :workflow :identifier :lbrace $_gen10 :rbrace -> Workflow( name=$1, body=$3 )

I'm not sure if this is an issue with the .wdl file, or if I need to update my wdl_runner, or if it's something else?

**Comment by bshifaw** [comment]
- The following material is provided by the GATK Team. Please post any questions or concerns to one of our forum sites : [GATK](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team/) , [FireCloud](https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team) , [WDL/Cromwell](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team). I would suggest WDL/Cromwell

But first make sure to you are using the latest version of [cromwell and wdl ](https://github.com/broadinstitute/cromwell/releases)

**Comment by marysweet** [comment]
I hadn't realized there was a new wdl_runner. I updated and it's working now. Thanks!
